version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "inside_trading_dev"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
      - app-net
  # backend:
  #   build: .
  #   depends_on:
  #     - db
  #   ports:
  #     - "4000:4000"
  #   environment:
  #     DATABASE_URL: ecto://postgres:postgres@db:5432/inside_trading_dev
  #   networks:
  #     - app-net

networks:
  app-net:
    driver: bridge
